image: docker.io/qazando/appium-maven

stages:
  - build

build:
  stage: build
  script:
    - curl -s --user "api:e98a94e3280b8ff7248f6abd834bda3b-77985560-c488e6b0" 
      "https://api.mailgun.net/v3/sandboxde23ed981ced404e91adf3f54b90e8eb.mailgun.org/messages"
      -F from='Excited User <mailgun@sandboxde23ed981ced404e91adf3f54b90e8eb.mailgun.org>'
      -F to=YOU@sandboxde23ed981ced404e91adf3f54b90e8eb.mailgun.org
      -F cc=herbert1078@gmail.com
      -F subject='Test results + report'
      -F text='Testing some Mailgun awesomeness!'