stages:
  - notify
  
variables:
  SLACK_WEBHOOK: https://hooks.slack.com/services/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
  SLACK_CHANNEL: geral
  SLACK_USERNAME: Bot

notify:
  stage: notify
  image: kromz/slack-notify:latest
  script:
    - curl -X POST \
    -H 'Content-type: application/json; charset=utf-8' \
    --data '{ "channel": "#geral", "username": "superbot", "icon_emoji": ":bot:", "text": "Foo", "attachments":[{"fallback":"New open task [Urgent]: <http://url_to_task|Test out Slack message attachments>","pretext":"New open task [Urgent]: <http://url_to_task|Test out Slack message attachments>","color":"#D00000","fields":[{"title":"Notes","value":"This is much easier than I thought it would be.","short":false}]}]}}' \ https://hooks.slack.com/services/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